name: SignSaya
description: "A system capable of interpreting these hand signals with Filipino Sign Language by providing technological solution that is specifically tailored to address frequently asked question for deaf tourists to enhance inclusivity through a multilingual feature."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0
  flutter_blue_plus: 
    # Add the version specified in the second pubspec.yaml file
    version: ^1.32.1
  scoped_model: ^2.0.0
  speech_to_text: ^6.1.1
  cupertino_icons: ^1.0.2
  translator: ^1.0.0
  sqflite: ^2.0.0
  path: ^1.8.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/images/backgroundHome.png
    - lib/images/backgroundTranslation.png
    - lib/images/infoButton.png
    - lib/images/settingsButton.png
    - lib/images/translationHome.png
    - lib/images/historyButton.png
    - lib/images/glovesPlaceholder.png
    - lib/images/delBttn.png
    - lib/images/micBttn.png
    - lib/images/informationPage.png
  uses-material-design: true
  fonts:
    - family: Intro Rust
      fonts:
        - asset: fonts/IntroRust-Base.otf
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Sans
      fonts:
        - asset: fonts/Sans.ttf

  plugin:
    platforms:
      android:
        package: com.lib.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
      ios:
        pluginClass: FlutterBluePlusPlugin
      macos:
        pluginClass: FlutterBluePlusPlugin
